# Dotfiles pre-commit configuration
# Matches GitHub Actions workflow for consistency

repos:
  # Basic file hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-executables-have-shebangs
      - id: check-merge-conflict

  # Canonical shell lint pipeline (shellcheck + shfmt + heuristics)
  - repo: local
    hooks:
      - id: shell-lint
        name: Shell lint (canonical pipeline)
        entry: scripts/lint-shell.sh
        language: system
        pass_filenames: false
        always_run: true
