repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
  # Using dedicated shfmt pre-commit wrapper repo (mvdan/sh clone was missing manifest in this environment)
  - repo: https://github.com/scop/pre-commit-shfmt
    # Tag pattern v<shfmt-version>-<packaging-rev>. Adjust if updating shfmt.
    rev: v3.12.0-2
    hooks:
      - id: shfmt
        args: ['-i', '2', '-ci', '-sr']
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck
        additional_dependencies: []
        files: |-
          ^(install\.sh|.*\.sh|\.zshrc|\.zsh/.*\.zsh)$
        exclude: |-
          (^|/)vendor/

# Local hooks (optional) for a quick aggregate shell lint run
  - repo: local
    hooks:
      - id: shell-lint-all
        name: shell-lint-all
        entry: bash scripts/lint-shell.sh
        language: system
        pass_filenames: false
        stages: [manual]
      - id: shell-audit-heuristics
        name: shell-audit-heuristics
        entry: bash scripts/audit-shell-style.sh
        language: system
        pass_filenames: false
        stages: [manual]
