name: Shell Lint

on:
  push:
    paths:
      - '**.sh'
      - '**.bash'
      - '**.zsh'
      - '.shellcheckrc'
      - '.shfmt.conf'
      - '.pre-commit-config.yaml'
      - '.github/workflows/shellcheck.yml'
  pull_request:
    paths:
      - '**.sh'
      - '**.bash'
      - '**.zsh'
      - '.shellcheckrc'
      - '.shfmt.conf'
      - '.pre-commit-config.yaml'
      - '.github/workflows/shellcheck.yml'
  workflow_dispatch:
    inputs:
      full_run:
        description: 'Run the full shell lint suite now'
        required: false
        default: 'true'

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies (shellcheck, shfmt)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y shellcheck zsh
          if ! command -v shfmt >/dev/null; then
            curl -sS https://webinstall.dev/shfmt | bash
            echo "$HOME/.local/bin" >> $GITHUB_PATH
          fi
      - name: Run canonical shell lint
        run: ./scripts/lint-shell.sh
